### ISSUE TITLE
Possible duplicate of gulp-compile-handlebars

### ISSUE THREAD

**Issue by guerrero** [shannonmoeller/gulp-hb#14]
I think that your repo has some benefits and differences from gulp-compile-handlebars but I think that the purpose of both is the same.

https://github.com/kaanon/gulp-compile-handlebars

@kaanon

**Comment by shannonmoeller** [comment]
Yep! Similar, but different.

**Comment by guerrero** [comment]
Ok, I'm sorry :)

**Comment by shannonmoeller** [comment]
No worries! :)
