### ISSUE TITLE
Add option for removing path from partial names

### ISSUE THREAD

**Issue by axelboc** [shannonmoeller/gulp-hb#18]
Hi,

This is in reference to closed issue #13.

I thought it was very convenient when the name of the partials did not include the path. I always prefix my partials with namespaces, so I never had any name clashes. Now, my templates are much more difficult to read.

Would it be possible to add an option to disable this feature so as to not having the path in the name of the partial?

Thanks a lot,
Axel

**Comment by shannonmoeller** [comment]
Added `parseDataName`, `parseHelperName`, and `parsePartialName`. Released as v2.5.0.

**Comment by axelboc** [comment]
So fast!
And great solution, thanks a lot!
