### ISSUE TITLE
YAML Front Matter Not Removed

### ISSUE THREAD

**Issue by brandonmerritt** [shannonmoeller/gulp-hb#20]
This probably isn't a bug, but I wanted to make sure. I have YAML Front-Matter in my HBS files. The front matter is just converted to text and not removed when using the plugin. I'm assuming that's normal and I need to use the front-matter plugin to deal with it?

**Comment by shannonmoeller** [comment]
Exactly. `gulp-hb` doesn't handle front-matter itself, so you'll need to use `gulp-data` or `gulp-front-matter`. The examples are just to show how they can work together.
