### ISSUE TITLE
v3 gulp-front-matter usage?

### ISSUE THREAD

**Issue by spacedawwwg** [shannonmoeller/gulp-hb#32]
I'm a little confused by the README as to how `gulp-front-matter` can be integrated now.

I have tried to follow the instructions:

```Javascript
.pipe(frontMatter({
      property: 'data.front',
      remove: true
    }))
```

```handlebars
{{file.data.front.title}}
```

does the above seem right to you?

**Comment by spacedawwwg** [comment]
```handlebars
{{front.title}} 
```

Boom, thats how to use it in this instance! (I'm going to let you get on with your life now @shannonmoeller!)

**Comment by shannonmoeller** [comment]
The [`file` option](https://github.com/shannonmoeller/gulp-hb#hboptions-transformstream) is now `false` by default as it was largely only included in v2 for the purpose of accessing `file.data`. Now that [`file.data`](https://github.com/shannonmoeller/gulp-hb#file-specific-data) is the default [context](https://github.com/shannonmoeller/handlebars-wax#context-and-rendering) for files, I didn't want `gulp-hb` to continue to override the `file` property anymore in case a user wanted that for something else.

Sorry for all the headaches these breaking changes caused. I hope your struggles help future googlers.

**Comment by shannonmoeller** [comment]
Thanks again for helping to make this plugin stable and usable.
