### ISSUE TITLE
Handlebars dependency

### ISSUE THREAD

**Issue by Billy-** [shannonmoeller/gulp-hb#36]
If you do not install the handlebars npm module and try to run gulp-hb you will get an error; `Cannot find module 'handlebars'`. Obviously. But the problem is there is no mention of this dependency as far as I can tell. And apart from that, why would you not just add it as an install dependency?

**Comment by shannonmoeller** [comment]
Handlebars is a dependency. My guess is that your original `npm install` of `gulp-hb` failed for some reason.

https://github.com/shannonmoeller/gulp-hb/blob/master/package.json#L44

**Comment by Billy-** [comment]
Right, not sure why I didn't look into this further.. Sorry! :confused:

**Comment by shannonmoeller** [comment]
No worries!
