### ISSUE TITLE
We need have *.hbs for input but *.html at output

### ISSUE THREAD

**Issue by ryuran** [shannonmoeller/gulp-hb#37]
Hello,

It's can be a stupid question but.
How to change extension from src file to dest (.hbs to .html) ?

Thanks

**Comment by shannonmoeller** [comment]
Sure thing! You're looking for [gulp-rename](https://www.npmjs.com/package/gulp-rename). You can use it before or after `gulp-hb` to change the extensions. I like to put it close to the `gulp.dest` when I can.

```js
var gulp = require('gulp');
var hb = require('gulp-hb');
var rename = require('gulp-rename');

gulp.src('src/**/*.hbs')
    .pipe(hb())
    .pipe(rename({ extname: '.html' })
    .pipe(gulp.dest('dest'))
```

**Comment by ryuran** [comment]
Thank you for your answers.
I use gulp-rename and it's works.
