### ISSUE TITLE
Errors being swallowed?

### ISSUE THREAD

**Issue by shannonmoeller** [shannonmoeller/gulp-hb#38]
Need to investigate whether gulp-hb is swallowing errors.

https://github.com/shannonmoeller/handlebars-wax/issues/7

**Comment by shannonmoeller** [comment]
@mendlik

**Comment by mendlik** [comment]
Sorry for such a long break.
I did small investigation it seems that handlebars does not generate errors.
I created an issue for that: https://github.com/wycats/handlebars.js/issues/1219

**Comment by shannonmoeller** [comment]
I'm going to close this issue in favor of the one you mention. Feel free to reopen, if needed.
