### ISSUE TITLE
Input .json sources to .hbs template to output .html

### ISSUE THREAD

**Issue by jpls93** [shannonmoeller/gulp-hb#51]
I forked this repository to display an [example](https://github.com/jpls93/gulp-hb/tree/master/example)  on what I need to do. Basically, I need to plug .json files to an .hbs template to produce .html files.

Sorry if I do not have enough technical know-how to discover how to do it myself.

If the example makes sense, let me know if I can send a pull request to have it merged.

**Comment by shannonmoeller** [comment]
Thank you for your interest in submitting a pull request. The pattern for rendering multiple data sources with the same template or templates is addressed in the [README](https://github.com/shannonmoeller/gulp-hb#multiple-data-sources). (Also see #46, #39, #27, and #26.)

**Comment by shannonmoeller** [comment]
@jpls93 Were you able to get this working?

**Comment by jpls93** [comment]
@shannonmoeller Hi Shannon, thanks for the follow-up. I've been reading articles about through2, Node.js streams and other relevant articles. I'll be working on this for the next few hours.

**Comment by jpls93** [comment]
@shannonmoeller I found your [code](https://github.com/shannonmoeller/tmp/blob/master/gulpfile.js) which satisfies my requirements.
