### ISSUE TITLE
importing inline css via helper

### ISSUE THREAD

**Issue by evromalarkey** [shannonmoeller/gulp-hb#52]
Hello,
I'm trying to import inline css via helper. eg. inline_css: fs.readFileSync('css/style.css','utf8')

But in the output the entities are converted.. example:
```
= to &#x3D; 
& to &amp;, 
```
is there any way to disable this?

**Comment by shannonmoeller** [comment]
Yep! Handlebars itself provides the solution. Use three curly braces instead of two:

```handlebars
<!-- insert escaped value -->
{{inline_css}}

<!-- insert raw value -->
{{{inline_css}}}
```

**Comment by evromalarkey** [comment]
I totally forgot about that, thanks a lot!
