### ISSUE TITLE
Partials as array get wrong namespace

### ISSUE THREAD

**Issue by MickL** [shannonmoeller/gulp-hb#55]
I found some weird behavior:

When passing an array to `.partials()` then the first namespace is correct but the second shows the full path on disk:

```
.pipe(
   hb({debug: true})
       .partials([
         'src/components/partial1/partial1.hbs',
         'src/components/partial1/partial2.hbs'
      ])
   )
```

```
partials:
      /Users/mickL/Documents/git/myproject/src/components/partial2 
     partial1
```

If the first is using a wildcard then all of those are correct, but from the beginning its the full path again:
```
.partials(['src/components/shared/**/*.hbs', 'src/components/base.hbs'])
```

All the same for using `hb({partials: [...]})`

**Comment by MickL** [comment]
Workaround: Just import EVERYTHING as a partial: .partial('components/**/*.hbs')

**Comment by shannonmoeller** [comment]
You need to specify a [`base` option](https://github.com/shannonmoeller/handlebars-wax#custom-names) for your first example:

```js
hb({debug: true})
    .partials([
        'src/components/partial1/partial1.hbs',
        'src/components/partial1/partial2.hbs'
    ], {
        base: __dirname + '/src/components/partial1'
    })
```

Alternatively, your workaround is actually the intended and recommended means of registering partials.
