### ISSUE TITLE
Custom partial helper

### ISSUE THREAD

**Issue by alxbenz** [shannonmoeller/gulp-hb#56]
Hi,

I want to create a custom partial helper.
e.g. `{{include partialanme}}` instead of `{{> partialname}}`

Is there a way to reference the partials from within the helper function?

**Comment by shannonmoeller** [comment]
Yep! Under the hood, `gulp-hb` uses the [`handlebars-wax`](http://npm.im/handlbars-wax) library. It supports a pattern where you [export a factory](https://npm.im/handlebars-wax#registering-partials-helpers-and-decorators) inside your custom helpers or partials files. That's how [`handlebarts-layouts` does it](https://github.com/shannonmoeller/handlebars-layouts/blob/master/index.js#L214-L228).
