### ISSUE TITLE
handlebars-helpers

### ISSUE THREAD

**Issue by theZimmee** [shannonmoeller/gulp-hb#8]
Hey, thanks for the module, I just started using it, just what I wanted! In your example you have:
```
'./node_modules/handlebars-helpers/lib/helpers/helpers-{dates,math}.js'
```
listed as a helper. I tried installing, but I got an error saying:
```
Cannot find module 'grunt'
```
Is handlebars-helpers compatible with gulp? I would really love to get the markdown helper helper you have there working...

Thanks again.

**Comment by shannonmoeller** [comment]
The `handlebars-helpers` version of certain helpers has a hard dependency on grunt to make use of some of those helpers. This dependency has been removed from their new helpers that will be announced along with Assemble 1.0, coming soon.

For now, you can try out their new markdown helper (without the grunt dependency) directly: https://github.com/helpers/helper-markdown

**Comment by theZimmee** [comment]
Thanks, this does work. Any idea when Assemble 1.0 will be released so I can check out `handlebars-helpers` in gulp?

**Comment by shannonmoeller** [comment]
I wish I did. I really like the new direction they took with it. Highly recommended for situations where `gulp-hb` doesn't quite cut it.

**Comment by theZimmee** [comment]
I'll have to check out out when it comes out, but `gulp-hb` is great!
Thanks again!
